### ISSUE TITLE
NPM package is broken

### ISSUE THREAD

**Issue by bebraw** [webgio/react-pagination#1]
Take a look at https://www.npmjs.com/package/react-pagination . I had a conversation with the NPM folks. Apparently the package was released using a very old and buggy version of NPM. Could you please republish it using a new version to make the package available?

**Comment by webgio** [comment]
Sorry, this repo doesn't relate with the npm package you mention. I didn't publish it on NPM... Could it be https://github.com/AdeleD/react-paginate ?

**Comment by bebraw** [comment]
Ah, that's it. Thanks! Sorry for the confusion.
